name: CI
on:
  push:
    branches:
      - main
      - dev
  pull_request: {}
env:
  JAVA_VERSION: "17"
  JAVA_DISTRIBUTION: "temurin"
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: "${{ env.JAVA_DISTRIBUTION }}"
          java-version: "${{ env.JAVA_VERSION }}"
      - name: Run unit tests
        run: |
          make -C src unit-test
        id: unit-tests
      - name: Run integration tests
        run: |
            make -C src smoke-test
        id: integration-tests
      - name: Run specification tests
        run: |
          make -C src spec-test
        id: spec-tests
